### ISSUE TITLE
Webinterface nicht erreichbar

### ISSUE THREAD

**Issue by kobaje** [n-thumann/IPTV-ReStream#1]
Hallo,

ich habe dein Programm bei c't entdeckt. Das ist genau was ich schon länger suche. Ich habe Docker installiert und den Container gestartet. Soweit alles ok. Doch ich erreiche das Webinterface unter 127.0.0.1:3000 nicht. Der browser meldet Verbindung abgewiesen. An der Firewall liegt es nicht. Kannst du mir da weiterhelfen (OS ist Win 10 Prof).

Grüße und Danke

Jens

**Comment by purejava** [comment]
Hi @kobaje,

ich teste die Software auch gerade, nachdem ich in der ct darüber gelesen habe 🙂
Bei mir läuft die Node.js app, sie ist erreichbar unter `localhost:3000`.

Hast du mal **localhost** anstatt **127.0.0.1** versucht?

VG Ralph

**Comment by n-thumann** [comment]
Moin @kobaje,
kannst du mir mal den Output von `docker ps`schicken, um sicherzustellen, dass die internen Ports des Containers an die des Hostsystem weitergereicht werden?
Habt ihr zufällig einen Link/Heftnummer, wo ihr dieses Projekt gefunden habt? :)

**Comment by kobaje** [comment]
Im aktuellen Heft 7/20. (https://www.heise.de/select/ct/2020/7/2000809370690961974)

PS C:\Users\Heimspeicher> docker ps
CONTAINER ID     IMAGE    COMMAND              CREATED              STATUS              PORTS    NAMES
75f366beba6b   nthumann/iptv-restream:latest   "node dist/app.js"   About a minute ago   Up About a minute       IPTV-ReStream

Sorry, weiss nicht wie ichs besser formatieren soll. Ports ist leer.

**Comment by kobaje** [comment]
> 
> 
> Hi @kobaje,
> 
> ich teste die Software auch gerade, nachdem ich in der ct darüber gelesen habe 🙂
> Bei mir läuft die Node.js app, sie ist erreichbar unter `localhost:3000`.
> 
> Hast du mal **localhost** anstatt **127.0.0.1** versucht?
> 
> VG Ralph

localhost hat auch nicht funktioniert

**Comment by n-thumann** [comment]
Du hast den Container - wie von c't beschrieben - mit `--network host` gestartet, richtig? Anscheinend hat aber diese Option unter nicht-Linux-System [keine Wirkung](https://docs.docker.com/network/host/) :/ Wenn du es mit Docker nutzen willst, klappt das also nur auf einem Linuxsystem.
Daher würde ich es direkt (ohne Docker) installieren, [hier](https://github.com/n-thumann/IPTV-ReStream#installation) die entsprechende Anleitung :)

**Comment by kobaje** [comment]
Hm, ok. Das stand nicht in der c't ;-) Ich probiers mal mit der anderen Variante.

**Comment by purejava** [comment]
Hi,

habe den Docker Container auf einem Mac gestartet mit `docker run -d --network host --restart always --name IPTV-ReStream nthumann/iptv-restream:latest`.

Wenn ich mich auf das CLI im Container verbinde ist zu sehen, dass die Anwendung läuft:
```
/app $ netstat -atpn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      1/node
tcp        0      0 0.0.0.0:50365           0.0.0.0:*               LISTEN      -
tcp        0      0 :::111                  :::*                    LISTEN      -
tcp        0      0 :::39237                :::*                    LISTEN      -
/app $ %   
```
Außerhalb des Containers ist sie jedoch nicht zu erreichen.

**Comment by kobaje** [comment]
Jetzt hänge ich bei tsc. Was muss ich da machen?

**Comment by n-thumann** [comment]
Du kannst TypeScript entweder über `npm install -g typescript` global nachinstallieren oder `./node_modules/typescript/bin/tsc` ausführen, das nach `npm install` automatisch heruntergeladen wird :)

**Comment by kobaje** [comment]
ok. Global installiert, ausgeführt. npm start ergibt folgenden Fehler:

C:\IPTV-ReStream-master>npm start

> iptv-restream@1.0.0 start C:\IPTV-ReStream-master
> node dist/app.js

NodeJS v13.0.2 (or higher) is required!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iptv-restream@1.0.0 start: `node dist/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iptv-restream@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Heimspeicher\AppData\Roaming\npm-cache\_logs\2020-03-15T11_38_43_817Z-debug.log

Oh mann, sorry, aber ich wusste schon warum ich den container favorisiert hatte... Das sind für mich böhmische Dörfer

**Comment by n-thumann** [comment]
Hast es fast geschafft 👍 Deine installierte NodeJS Version ist zu alt. Es muss v13.0.2 oder höher installiert sein, also einfach [hier](https://nodejs.org/en/) die aktuelle Version herunterladen und installieren :)

**Comment by kobaje** [comment]
super, habs grad selber gemerkt. jetzt scheint es zu gehen DANKE

**Comment by n-thumann** [comment]
Sehr gut! Dann mache ich diese Issue mal zu ✌️

**Comment by purejava** [comment]
[Das](https://stackoverflow.com/questions/41049677/connection-refused-on-docker-node-container) ist die Ursache des Problems.

Ergänzt man auf dem Mac ein `-e HOST="0.0.0.0"` beim Starten des Containers, ist er von außen erreichbar.

**Comment by kobaje** [comment]
Du meinst so:
docker run -d --network host --restart always --name IPTV-ReStream nthumann/iptv-restream:latest -e HOST="0.0.0.0"
Das funktioniert bei mir nicht.

**Comment by purejava** [comment]
> Du meinst so:
> docker run -d --network host --restart always --name IPTV-ReStream nthumann/iptv-restream:latest -e HOST="0.0.0.0"
> Das funktioniert bei mir nicht. Gleiches Problem.

Nein, sondern so:
```
docker run -d --restart always -p 3000:3000 -e HOST="0.0.0.0" --name IPTV-ReStream nthumann/iptv-restream:latest
```
Die Optionen müssen vor der Bezeichnung des image angegeben werden:
```
ralph@machine ~ % docker run --help 

Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```
> Habe es mit der js installation zwar hinbekommen auf das webinterface zugreifen zu können, Kanäle werden angezeigt, VLC spielt aber nix ab.

Öffnet dafür bitte einen separaten issue auf GitHub.

**Comment by n-thumann** [comment]
> > Habe es mit der js installation zwar hinbekommen auf das webinterface zugreifen zu können, Kanäle werden angezeigt, VLC spielt aber nix ab.
> 
> Öffne dafür bitte einen separaten issue auf GitHub.
Genau :)
