### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by dMopp** [n-thumann/IPTV-ReStream#10]
npm start

> iptv-restream@1.0.0 start /home/restream/IPTV-ReStream
> node dist/app.js

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module '/home/restream/IPTV-ReStream/dist/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iptv-restream@1.0.0 start: `node dist/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iptv-restream@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/restream/.npm/_logs/2020-06-30T14_23_18_682Z-debug.log

Log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle iptv-restream@1.0.0~prestart: iptv-restream@1.0.0
6 info lifecycle iptv-restream@1.0.0~start: iptv-restream@1.0.0
7 verbose lifecycle iptv-restream@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle iptv-restream@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/restream/IPTV-ReStream/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle iptv-restream@1.0.0~start: CWD: /home/restream/IPTV-ReStream
10 silly lifecycle iptv-restream@1.0.0~start: Args: [ '-c', 'node dist/app.js' ]
11 silly lifecycle iptv-restream@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle iptv-restream@1.0.0~start: Failed to exec start script
13 verbose stack Error: iptv-restream@1.0.0 start: `node dist/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid iptv-restream@1.0.0
15 verbose cwd /home/restream/IPTV-ReStream
16 verbose Linux 5.6.0-2-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error iptv-restream@1.0.0 start: `node dist/app.js`
22 error Exit status 1
23 error Failed at the iptv-restream@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dMopp** [comment]
This can be fixed by:

1.) npm install typescript
2.) run node_modules/typescript/bin/tsc

Afterwards it can be started

**Comment by n-thumann** [comment]
You´re right, the TS code needs to be transpiled to JS for Node to run. TypeScript should be installed automatically (see [package.json](https://github.com/n-thumann/IPTV-ReStream/blob/master/package.json#L29)) and `tsc` needs to be run manually (see [README.md](https://github.com/n-thumann/IPTV-ReStream/blob/master/README.md#installation)) ✌️
