### ISSUE TITLE
Restreaming

### ISSUE THREAD

**Issue by williamiptv** [n-thumann/IPTV-ReStream#107]
I din't get it, i mean if i subcribe paid iptv with My isp but that only give 1 device, can i using this metode to restream To another device(More than 5 device) Without pay more to my isp ? specialy Not using Vlc but like another Modifcation App ?

**Comment by n-thumann** [comment]
Yes, but only if your ISP utilizes source-specific multicast (UDP) for receiving the stream. Then IPTV-ReStream is able to receive it once from the ISP and re-broadcast it to as many devices as you want.
Other apps are theoretically supported, but practically only VLC can play this properly.

**Comment by williamiptv** [comment]
Actuly I know some IPTV Restreaming seler But i can't get any data Like channel list or M3U files because it's already in the form of an application , so I need pay and Get some username and password to acses Channel in application for one device ,Can you have solution like this?? So i can only pay for one device And Restream To another device?? Or maybe i still need some Source Link/list Data Like M3U to Restream using this method?

**Comment by n-thumann** [comment]
You definitely need some kind of stream source. You can probably extract it from the app. Nevertheless IPTV-ReStream cannot handle any kind of source authentication to access the stream, which is probably needed in your case. You'd need to heavily adjust IPTV-ReStream to your demands.
