### ISSUE TITLE
[FEATURE REQUEST] Specify Interface/IP for Multicast Source

### ISSUE THREAD

**Issue by dMopp** [n-thumann/IPTV-ReStream#11]
I have a VM running in 2 networks and Multicast in only working in one of them...

eG:
Network 1: 192.168.0.0/24 --> Clients
Network 2: 192.168.178.0/24 --> Multicast Avaiable

What i cant to archive:
Let my Clients from Network 1 Stream over HTTP while the Multicast Stream is comming from Network 2

udpxy:  udpxy -p 9090 -S -a 192.168..55 -m 192.168.178.20
-a = Listen Interface
-m = Multicast Interface

**Comment by n-thumann** [comment]
Sounds great, thanks for the idea! I´ve added it to my TODOs and will let you know here, when there are any updates. 😊

**Comment by n-thumann** [comment]
Would you mind to checkout the `dev` branch? I´ve implemented a new [environment variable](https://github.com/n-thumann/IPTV-ReStream/tree/dev#environment-variables) called `MCAST_IF` to specify the interface to join the multicast group with, so `192.168.178.20` in your case. I´m happy about any feedback 😊

**Comment by n-thumann** [comment]
I´ve just merged `dev` into `master`, so that this feature is now available. It´s also already built as a Docker image ✌️
