### ISSUE TITLE
Error occurs when I run npm run build

### ISSUE THREAD

**Issue by HESSEBO** [n-thumann/IPTV-ReStream#165]
Hi and thanks for the great project

When I run npm run build I get the following error: 

error TS6059: File '/home/pi/IPTV-ReStream/IPTV-ReStream/src/app.ts' is not under 'rootDir' '/home/pi/IPTV-ReStream/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by include pattern '**/*' in '/home/pi/IPTV-ReStream/tsconfig.json'

Please advice.

**Comment by n-thumann** [comment]
Hi ✌🏻
It looks like there's an issue with you local directory structure: The `app.ts` on your machine is at `/home/pi/IPTV-ReStream/IPTV-ReStream/src/` while it's suppose to be at `/home/pi/IPTV-ReStream/src/`
How did you download this project? Did you cloned it from GitHub? This will likely solve itself, if you re-download it.

**Comment by n-thumann** [comment]
Hi, have you been able to solve this issue?

**Comment by n-thumann** [comment]
Have you set the `HOST` environment variable accordingly? The default value is `127.0.0.1`, so the service won't be reachable from the outside per default (see `HOST=127.0.0.1` below):
```
➜  IPTV-ReStream git:(main) DEBUG="iptv-restream:*" npm start

> iptv-restream@1.4.6 start
> node dist/app.js

  iptv-restream:config Config loaded: HOST=127.0.0.1, PORT=3000, MCAST_IF=0.0.0.0, XSPF_PROTOCOL=, XSPF_HOST=, XSPF_PATH_PREFIX=, ALLOW_UNKNOWN=false +0ms
  iptv-restream:server Listening on port 127.0.0.1:3000... +0ms
```

**Comment by n-thumann** [comment]
Did you managed to get it working? :)

**Comment by n-thumann** [comment]
Let me know, if you need further assistance. Closing this until then :)
