### ISSUE TITLE
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3

### ISSUE THREAD

**Issue by roommini** [n-thumann/IPTV-ReStream#32]
[root@xspf IPTV-ReStream]# npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 308 packages in 2.097s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[root@xspf IPTV-ReStream]#

**Comment by n-thumann** [comment]
This is caused by package `nodemon` trying to install `fsevents` as an optional package. As `fsevents` is only working on macOS, this warning is thrown and can be ignored. Nevertheless, I´ve removed `nodemon`, so as of the current commit this warning should be gone ✌️
