### ISSUE TITLE
Webinterface über Netzwerk erreichbar?

### ISSUE THREAD

**Issue by videonaut** [n-thumann/IPTV-ReStream#4]
Ich würde gern von einem anderen Rechner aus auf das Webinterface zugreifen, da es unter Libreelec auf dem RPi keinen Webbrowser gibt. Ist das möglich?

**Comment by n-thumann** [comment]
Ja, dazu einfach die Umgebungsvariable ´HOST´ auf die gewünscht IP Adresse ändern ✌️

**Comment by videonaut** [comment]
Danke für die schnelle Antwort. Läuft jetzt.
