### ISSUE TITLE
Cannot GET /iptv/live/87.141.215.251@232.0.20.35:10000

### ISSUE THREAD

**Issue by stueja** [n-thumann/IPTV-ReStream#6]
Ich habe den Container mit 
```
docker run -d --network host --restart always --name IPTV-ReStream -e HOST=0.0.0.0 -e PORT=1337 -e XSPF_PROTOCOL="http" -e XSPF_PATH_PREFIX="/iptv" -e ALLOW_UNKNOWN="true" nthumann/iptv-restream:latest
```
gestartet (auf Arch Linux), bisher ohne reverse proxy.

Ich kann das Webinterface von einem anderen Rechner aus erreichen. "Status" sagt `No connections`, "Stations" gibt mir eine Senderliste. Ein Klick auf den Play-Button unter "View Now" ergibt 
```
Cannot GET /iptv/live/87.141.215.251@232.0.20.35:10000
```

Was mache ich falsch?

**Comment by n-thumann** [comment]
Klapp es, wenn du den Container ohne `XSPF_PATH_PREFIX`startest? Das ist für die Benutzung zusammen mit einem Reverse Proxy gedacht, damit dieser den Traffic entsprechend weiterleiten kann ✌️

**Comment by stueja** [comment]
Das funktioniert ganz wunderbar! Dankeschön!

**Comment by stueja** [comment]
Also, ich sitz auf dem Schlauch, glaube ich.
Ich starte den aktuellen Container auf meinem lokalen Rechner durch die angebotene `docker-compose.yml`, aus der ich XSPF-Variablen auskommentiert habe:

```
version: "3.8"
services:
  iptv-restream:
    image: nthumann/iptv-restream:latest
    build:
      context: .
    network_mode: host
    restart: always
    container_name: IPTV-ReStream
    environment:
      HOST: "127.0.0.1"
      PORT: 3000
      # MCAST_IF: "0.0.0.0"
      # XSPF_PROTOCOL: "http"
      # XSPF_HOST: "127.0.0.1:3000"
      # XSPF_PATH_PREFIX: "/iptv"
      ALLOW_UNKNOWN: "true"
      DEBUG: "iptv-restream:*"
```

Ich rufe `http://127.0.0.1:3000` auf, bekomme das Webinterface, der Button `Open raw stream` bietet mir einen Download an und der Button `Open stream in VLC` sagt `Could not read file: vlc://http//127.0.0.1:3000/live/87.141.215.251@232.0.20.35:10000` (in Chromium über xdg-open) bzw. `Your input can't be opened:
VLC is unable to open the MRL 'vlc://http://127.0.0.1:3000/live/87.141.215.251@232.0.10.135:10000'. Check the log for details.` (in VLC).
(Der andere Rechner, auf dem ein ganz alter Container lief, ist leider hopps gegangen.)

Was muß ich denn tun, um den VLC-Stream sehen zu können?

**Comment by n-thumann** [comment]
Irgendwie scheint dein Rechner mit der `vlc://` URL nicht klarzukommen. Ursprünglich gedacht und getestet habe ich den für die VLC iOS App. Unter iOS öffnet sich auch weiterhin VLC mit der richtigen URL.

Du musst den Link des `Open raw stream`-Buttons kopieren und in VLC einfügen (oder die XSPF Playlist nutzen). Das ist die gleiche URL, nur ohne `vlc://`-Präfix :v:

**Comment by stueja** [comment]
Aah, OK, dann mache ich das so -- vielen Dank! :)
