### ISSUE TITLE
Senderbezeichnungen herausfinden?

### ISSUE THREAD

**Issue by stueja** [n-thumann/IPTV-ReStream#7]
Im README ist ja erwähnt, daß ein Sender auch über `stations/ZDFSD` angesprochen werden kann. Gibt es irgendwo eine Liste, in der man die anderen Sender nachsehen kann? 
Ist es `ARDHD` oder `DasErsteHD`? 
Wird `NDR Mecklenburg-Vorpommern SD` irgendwie abgekürzt oder so gelassen? 
Spielt Groß- und Kleinschreibunng eine Rolle?
Vielen Dank!

**Comment by n-thumann** [comment]
Alle Daten stammen aus dieser [Senderliste](https://db.iptv.blog/multicastadressliste.json), genau wie sie im Webinterface stehen. Die Sendernamen werden dann aus `channel_name` und `media_definition` gebildet, z.B. `ZDF HD`. Daher ist es auch `Das Erste HD` und nicht `ARD HD` 😊 
Für die Abkürzung spielen sowohl Groß-/Kleinschreibung als auch Leerzeichen keine Rolle. Sollte `SD` oder `HD` in der Abkürzung fehlen, wird der Sender genommen, der in der Senderliste weiter oben steht, also die HD-Variante: `"Das Erste HD" == "das erste hd" == "dasErstehd" == "Das Erste"`.
Für `NDR Mecklenburg-Vorpommern SD` kannst du also `/live/station/NDR Mecklenburg-Vorpommern SD`, `/live/station/NDR Mecklenburg-Vorpommern` oder sogar nur `/live/station/NDRM` schreiben ✌️

**Comment by stueja** [comment]
Danke! :)
