### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by dMopp** [n-thumann/IPTV-ReStream#9]
npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
**npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})**

**Comment by n-thumann** [comment]
This warning occurs, because [fsevents](https://www.npmjs.com/package/fsevents) is an macOS-only package and therefore cannot be installed on non-macOS systems. It´s perfectly fine to ignore this 😊
