### ISSUE TITLE
Restream existing live .TS stream

### ISSUE THREAD

**Issue by matrixebiz** [n-thumann/IPTV-ReStream#95]
Hello, I would like to know if your program allows for source locations to be .ts files, eg: http://myserver.com/livevideo.ts and the output readable by tv streaming devices? Thanks

**Comment by n-thumann** [comment]
No, this not possible. IPTV-ReStream is intended to received source-specific multicast traffic and proxy that via HTTP. My application outputs these transport streams (TS files) and they cannot be used as an input.
If you already have a TS file you want to make available via HTTP, you can easily use any webserver or VLCs or ffmpegs streaming options :)
